apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-ns-prod
  namespace: ns-prod
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "20"
